export interface CityInformation {
  name: string
  lat: number
  lon: number
  country: string
  state?: string
  local_names?: LocalNames
}

export interface LocalNames {
  sh?: string
  es: string
  sm?: string
  ml?: string
  pt?: string
  ay?: string
  el?: string
  bn?: string
  ce?: string
  ee?: string
  ig?: string
  ln?: string
  is?: string
  fa?: string
  qu?: string
  ku?: string
  tn?: string
  gl?: string
  sw?: string
  bs?: string
  lb?: string
  feature_name?: string
  sr?: string
  ms?: string
  vi?: string
  eo?: string
  et?: string
  ka?: string
  oc?: string
  rm?: string
  ro?: string
  tw?: string
  fi?: string
  uz?: string
  ia?: string
  fr?: string
  hu?: string
  ko?: string
  si?: string
  la?: string
  bm?: string
  cs?: string
  so?: string
  yo?: string
  gd?: string
  nv?: string
  io?: string
  te?: string
  tl?: string
  ht?: string
  no?: string
  pa?: string
  ascii?: string
  fy?: string
  kk?: string
  da?: string
  kw?: string
  be?: string
  ug?: string
  sd?: string
  sl?: string
  tg?: string
  lv?: string
  th?: string
  fo?: string
  dv?: string
  za?: string
  ar: string
  mr?: string
  sa?: string
  bo?: string
  gn?: string
  ga?: string
  de?: string
  tr?: string
  kn?: string
  pi?: string
  st?: string
  ur?: string
  ja?: string
  br?: string
  li?: string
  sg?: string
  nn?: string
  gv?: string
  mg?: string
  en: string
  eu?: string
  sc?: string
  hy?: string
  yi?: string
  cy?: string
  bg?: string
  tk?: string
  ps?: string
  xh?: string
  sn?: string
  ne?: string
  bh?: string
  zh?: string
  ky?: string
  id?: string
  cv?: string
  sv?: string
  gr?: string
  av?: string
  mn?: string
  hi?: string
  ba?: string
  af?: string
  lt?: string
  am?: string
  uk?: string
  mk?: string
  ha?: string
  hr?: string
  my?: string
  az?: string
  nl?: string
  jv?: string
  ta?: string
  tt?: string
  mi?: string
  os?: string
  ru: string
  ks?: string
  ty?: string
  ca?: string
  vo?: string
  it?: string
  ie?: string
  pl?: string
  se?: string
  sq?: string
  zu?: string
  he?: string
  co?: string
  an?: string
  as?: string
  ny?: string
  sk?: string
  ts?: string
  bi?: string
  gu?: string
  na?: string
  ik?: string
  iu?: string
  lo?: string
  wo?: string
  ki?: string
  fj?: string
  cu?: string
  kv?: string
  km?: string
  kl?: string
  wa?: string
  su?: string
  ff?: string
  to?: string
  mt?: string
  or?: string
  ab?: string
  om?: string
}
